[package]
name = "ewma_GVI"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete = "0.1.9"
concrete-npe = "*"
concrete-commons = "*"
ndarray = "*"
ndarray-csv = "*"
csv = "*"
serde = "*"
